// <auto-generated />
using System;
using ErpConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121200509_AddSalaryTable")]
    partial class AddSalaryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Borrow")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProofFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProofType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.PurchaseSlip", b =>
                {
                    b.Property<int>("PurchaseSlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SlipDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseSlipId");

                    b.HasIndex("PartyId");

                    b.ToTable("PurchaseSlips");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.SalaryRecord", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AbsentDays")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BorrowRepayment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeductionPerDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinalSalary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PresentDays")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDeduction")
                        .HasColumnType("TEXT");

                    b.HasKey("SalaryId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.PurchaseSlip", b =>
                {
                    b.HasOne("ErpConsoleApp.Database.Models.Party", "Party")
                        .WithMany("PurchaseSlips")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.SalaryRecord", b =>
                {
                    b.HasOne("ErpConsoleApp.Database.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Party", b =>
                {
                    b.Navigation("PurchaseSlips");
                });
#pragma warning restore 612, 618
        }
    }
}
