// <auto-generated />
using System;
using ErpConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110185824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ErpConsoleApp.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            Name = "XYZ Party"
                        },
                        new
                        {
                            PartyId = 2,
                            Name = "Main Supplier Inc."
                        },
                        new
                        {
                            PartyId = 3,
                            Name = "Local Hardware"
                        });
                });

            modelBuilder.Entity("ErpConsoleApp.PurchaseSlip", b =>
                {
                    b.Property<int>("PurchaseSlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseSlipId");

                    b.HasIndex("PartyId");

                    b.ToTable("PurchaseSlips");
                });

            modelBuilder.Entity("ErpConsoleApp.PurchaseSlip", b =>
                {
                    b.HasOne("ErpConsoleApp.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });
#pragma warning restore 612, 618
        }
    }
}
