// <auto-generated />
using System;
using ErpConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119180221_AddPaidAmount")]
    partial class AddPaidAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.PurchaseSlip", b =>
                {
                    b.Property<int>("PurchaseSlipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SlipDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseSlipId");

                    b.HasIndex("PartyId");

                    b.ToTable("PurchaseSlips");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.PurchaseSlip", b =>
                {
                    b.HasOne("ErpConsoleApp.Database.Models.Party", "Party")
                        .WithMany("PurchaseSlips")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("ErpConsoleApp.Database.Models.Party", b =>
                {
                    b.Navigation("PurchaseSlips");
                });
#pragma warning restore 612, 618
        }
    }
}
